// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CostumerEvents.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Barigui.Prototipo.Events {

  /// <summary>Holder for reflection information generated from CostumerEvents.proto</summary>
  public static partial class CostumerEventsReflection {

    #region Descriptor
    /// <summary>File descriptor for CostumerEvents.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CostumerEventsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb3N0dW1lckV2ZW50cy5wcm90bxIYQmFyaWd1aS5Qcm90b3RpcG8uRXZl",
            "bnRzGh5nb29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8iMAoHRXZlbnRJ",
            "ZBIRCglSZXF1ZXN0SWQYASABKAkSEgoKQ3VzdG9tZXJJZBgCIAEoCSKEAQoV",
            "Q3VzdG9tZXJJbmZvSW5zZXJ0aW9uEi0KAklkGAEgASgLMiEuQmFyaWd1aS5Q",
            "cm90b3RpcG8uRXZlbnRzLkV2ZW50SWQSDAoETm9tZRgCIAEoCRINCgVFbWFp",
            "bBgDIAEoCRIQCghUZWxlZm9uZRgEIAEoCRINCgVJZGFkZRgFIAEoCUIbqgIY",
            "QmFyaWd1aS5Qcm90b3RpcG8uRXZlbnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Barigui.Prototipo.Events.EventId), global::Barigui.Prototipo.Events.EventId.Parser, new[]{ "RequestId", "CustomerId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Barigui.Prototipo.Events.CustomerInfoInsertion), global::Barigui.Prototipo.Events.CustomerInfoInsertion.Parser, new[]{ "Id", "Nome", "Email", "Telefone", "Idade" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EventId : pb::IMessage<EventId> {
    private static readonly pb::MessageParser<EventId> _parser = new pb::MessageParser<EventId>(() => new EventId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Barigui.Prototipo.Events.CostumerEventsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventId(EventId other) : this() {
      requestId_ = other.requestId_;
      customerId_ = other.customerId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventId Clone() {
      return new EventId(this);
    }

    /// <summary>Field number for the "RequestId" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CustomerId" field.</summary>
    public const int CustomerIdFieldNumber = 2;
    private string customerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CustomerId {
      get { return customerId_; }
      set {
        customerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EventId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      if (CustomerId != other.CustomerId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (CustomerId.Length != 0) hash ^= CustomerId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (CustomerId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CustomerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (CustomerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomerId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventId other) {
      if (other == null) {
        return;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.CustomerId.Length != 0) {
        CustomerId = other.CustomerId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
          case 18: {
            CustomerId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CustomerInfoInsertion : pb::IMessage<CustomerInfoInsertion> {
    private static readonly pb::MessageParser<CustomerInfoInsertion> _parser = new pb::MessageParser<CustomerInfoInsertion>(() => new CustomerInfoInsertion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CustomerInfoInsertion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Barigui.Prototipo.Events.CostumerEventsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CustomerInfoInsertion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CustomerInfoInsertion(CustomerInfoInsertion other) : this() {
      id_ = other.id_ != null ? other.id_.Clone() : null;
      nome_ = other.nome_;
      email_ = other.email_;
      telefone_ = other.telefone_;
      idade_ = other.idade_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CustomerInfoInsertion Clone() {
      return new CustomerInfoInsertion(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::Barigui.Prototipo.Events.EventId id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Barigui.Prototipo.Events.EventId Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Nome" field.</summary>
    public const int NomeFieldNumber = 2;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Email" field.</summary>
    public const int EmailFieldNumber = 3;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Telefone" field.</summary>
    public const int TelefoneFieldNumber = 4;
    private string telefone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Telefone {
      get { return telefone_; }
      set {
        telefone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Idade" field.</summary>
    public const int IdadeFieldNumber = 5;
    private string idade_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Idade {
      get { return idade_; }
      set {
        idade_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CustomerInfoInsertion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CustomerInfoInsertion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (Nome != other.Nome) return false;
      if (Email != other.Email) return false;
      if (Telefone != other.Telefone) return false;
      if (Idade != other.Idade) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Telefone.Length != 0) hash ^= Telefone.GetHashCode();
      if (Idade.Length != 0) hash ^= Idade.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nome);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (Telefone.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Telefone);
      }
      if (Idade.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Idade);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Telefone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Telefone);
      }
      if (Idade.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Idade);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CustomerInfoInsertion other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          Id = new global::Barigui.Prototipo.Events.EventId();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Telefone.Length != 0) {
        Telefone = other.Telefone;
      }
      if (other.Idade.Length != 0) {
        Idade = other.Idade;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (id_ == null) {
              Id = new global::Barigui.Prototipo.Events.EventId();
            }
            input.ReadMessage(Id);
            break;
          }
          case 18: {
            Nome = input.ReadString();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            Telefone = input.ReadString();
            break;
          }
          case 42: {
            Idade = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
